export const PRODUCT_ACTIONTYPES = {
    PRODUCT_CATEGORY_START: 'PRODUCT_CATEGORY_START',
    PRODUCT_CATEGORY_SUCCESS:'PRODUCT_CATEGORY_SUCCESS',
    PRODUCT_CATEGORY_ERROR:'PRODUCT_CATEGORY_ERROR' 
}